#!/bin/bash

addUser() {
    USERNAME="$1"
    PASSWORD="$2"

    id "$USERNAME" &>/dev/null || useradd -m -s /bin/bash "$USERNAME"
    echo "$USERNAME:$PASSWORD" | chpasswd
    usermod -aG wheel "$USERNAME"
}

addUser "Achraf_ELALAMI" '@chr@f3l@l@m!$'
addUser "Anas_LAARIBI" '@n@$L@@r!b!@'
addUser "Oumayma_REDISSI" '0um@ym@R3d!$'
addUser "Karim_SEFFAR" 'K@r!m$3ff@r$'
addUser "Fathi_JIRARI" 'F@th!J!r@r!$'
addUser "Sara_mehdaoui" '$@r@m3hd@ou!$'
addUser "Mehdi_YACOUBI" 'M3hd!Y@coub!@'
addUser "Adam_BEKKOUCHE" '@d@mB3kk0uch3$'
addUser "Ahmed_ARFAOUI" '@hm3d@rf@ou!@'
addUser "Mamoun_BERRADA" 'M@m0unB3rr@d@$'
addUser "Souhail_TORCHI" '$ouh@!T0rch!$'
addUser "Martin_SORO" 'M@rt!n$0r0$'
addUser "Annick" '@nn!ck$$'
addUser "Mohamed_LAHSAINI" 'Moh@m3dL@h$@!n!$'
addUser "youssef_MSADDEK" 'you$$3fM$@dd3k$'
addUser "mohamed_BENTTALEB" 'moh@B3ntt@l3b$'
addUser "ASMAE_TIGHA" '@$m@3T!gh@$'
addUser "aicha_HMIMOUCH" '@!ch@Hm!m0uch$'
addUser "nassim_FATTAHI" 'n@$$!mF@th@h!$'
addUser "Taha_BOUKAA" 'T@h@B0uk@@$'
addUser "Hamza_LEKHAL" 'H@mz@L3kh@l$'
addUser "Ismail_ZAHIR" '!$m@!L@Za$'
addUser "Lina_MEKKOURI" 'L!n@M3kk0ur!$'
addUser "Mehdi_GHANEME" 'M3hd!Gh@n3m3$'

echo "All 24 users created and added to wheel group successfully."
